CREATE TABLE STUDY_MANAGER (
id INTEGER PRIMARY KEY AUTOINCREMENT,
--1
title VARCHAR,
--2
content VARCHAR,
--3
process INTEGER,
--4
end_date TIMESTAMP
)

CREATE TABLE STUDY_HISTORY(
id INTEGER PRIMARY KEY AUTOINCREMENT,
plain_id INTEGER,
content VARCHAR,
img VARCHAR,
create_date TIMESTAMP
)

DROP TABLE  IF EXISTS STUDY_MANAGER
DROP TABLE  IF EXISTS STUDY_MANAGER